## template: jinja
#cloud-config
hostname: ping-monitor
users:
  #- default
  - name: ansible
    groups:
      - sudo
      - docker
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGlKIqgyWzF5u6GZOe0FAHoAuHkU/XHPB113r32k629X ping-monotor yandex cloud

packages:
  - tree
  - make
  - jq
  # Docker
  - docker-ce
  - docker-ce-cli
  - containerd.io

apt:
  sources:
    docker:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable"
      # Get keyid: curl -sL https://download.docker.com/linux/ubuntu/gpg | gpg
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

# device_aliases:
#   data0: /dev/disk/by-id/virtio-data-disk
disk_setup:
  /dev/disk/by-id/virtio-data-disk:
    table_type: gpt
    layout: true
    overwrite: false
fs_setup:
  - label: data0
    filesystem: ext4
    device: /dev/disk/by-id/virtio-data-disk
    partition: auto
mounts:
 - [ /dev/disk/by-id/virtio-data-disk-part1, /var/lib/docker, auto, "defaults" ]

#
# bootcmd:
#   - echo "I am booted as '$(whoami)'"

# runcmd:
#   - echo "I am runned as '$(whoami)'"
#   - echo "Availability zone {{ v1.availability_zone }}" > /az.txt
#   - "I am a ..."
